// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqMMvq9fcqxnwyQaKQIhb23ciLWVJedaQ',
    appId: '1:213744390392:web:4f602fb77a75eb959c6b0d',
    messagingSenderId: '213744390392',
    projectId: 'didtask-75b2d',
    authDomain: 'didtask-75b2d.firebaseapp.com',
    storageBucket: 'didtask-75b2d.appspot.com',
    measurementId: 'G-PJWQ98F73J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHQ6nDWrPQGQI2tV10B_YeRR6dPVZpvgQ',
    appId: '1:213744390392:android:c457a6e9230fccd09c6b0d',
    messagingSenderId: '213744390392',
    projectId: 'didtask-75b2d',
    storageBucket: 'didtask-75b2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH4HjjYtyTYWIRLRdnAdac1w4HfcCAAJ0',
    appId: '1:213744390392:ios:71962d78769703999c6b0d',
    messagingSenderId: '213744390392',
    projectId: 'didtask-75b2d',
    storageBucket: 'didtask-75b2d.appspot.com',
    androidClientId: '213744390392-42tfqaaufmrs17t20h0kparsqkj4iliu.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskeye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH4HjjYtyTYWIRLRdnAdac1w4HfcCAAJ0',
    appId: '1:213744390392:ios:71962d78769703999c6b0d',
    messagingSenderId: '213744390392',
    projectId: 'didtask-75b2d',
    storageBucket: 'didtask-75b2d.appspot.com',
    androidClientId: '213744390392-42tfqaaufmrs17t20h0kparsqkj4iliu.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskeye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqMMvq9fcqxnwyQaKQIhb23ciLWVJedaQ',
    appId: '1:213744390392:web:1d35dac4f11bf8e19c6b0d',
    messagingSenderId: '213744390392',
    projectId: 'didtask-75b2d',
    authDomain: 'didtask-75b2d.firebaseapp.com',
    storageBucket: 'didtask-75b2d.appspot.com',
    measurementId: 'G-EWLFTWR7E3',
  );
}
